# Generated by Django 2.0 on 2019-10-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20191024_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
